{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-prism.fullname" . }}
  labels:
    {{- include "model-prism.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  MONGO_URI: {{ include "model-prism.mongoUri" . | b64enc | quote }}
  JWT_SECRET: {{ (default (randAlphaNum 64) .Values.secrets.jwtSecret) | b64enc | quote }}
  ENCRYPTION_KEY: {{ (default (randAlphaNum 32) .Values.secrets.encryptionKey) | b64enc | quote }}
  {{- if .Values.secrets.adminSecret }}
  ADMIN_SECRET: {{ .Values.secrets.adminSecret | b64enc | quote }}
  {{- end }}
{{- end }}
