/**
 * IDE Config Generator — Admin + Public API endpoints
 *
 * Admin (JWT auth via /api/prism/ide-config/*):
 *   GET  /models?tenant=<id>      — models for a specific tenant (with tier advice)
 *   POST /generate                — generate config file content
 *   GET  /settings                — public-page settings
 *   PUT  /settings                — update public-page settings
 *   GET  /tenants                 — list all tenants (for admin dropdown)
 *
 * Public (no auth, mounted at /api/prism/public/ide-config/*):
 *   GET  /tenants                 — tenants enabled for public config (slug+name only)
 *   GET  /models?tenant=<slug>    — models for a public-enabled tenant
 *   POST /generate                — generate config for a public-enabled tenant
 */
import { Router } from 'express';
import Provider from '../../models/Provider.js';
import Tenant from '../../models/Tenant.js';
import SystemConfig from '../../models/SystemConfig.js';
import { anyUser, adminOnly } from '../../middleware/rbac.js';

const router = Router();

// ── Shared helpers ───────────────────────────────────────────────────────────

const TIER_ADVICE = {
  micro:    { cost: 'negligible', recommendation: 'autocomplete' },
  minimal:  { cost: 'very low',   recommendation: 'autocomplete' },
  low:      { cost: 'low',        recommendation: 'autocomplete, small tasks' },
  medium:   { cost: 'moderate',   recommendation: 'general coding, code review, debugging' },
  advanced: { cost: 'moderate',   recommendation: 'complex coding, architecture questions' },
  high:     { cost: 'high',       recommendation: 'agentic SWE, complex refactoring, security reviews' },
  ultra:    { cost: 'very high',  recommendation: null },
  critical: { cost: 'very high',  recommendation: null },
};

function enrichModel(m, providerName) {
  const advice = TIER_ADVICE[m.tier] || {};
  const entry = { id: m.id, name: m.id, provider: providerName, tier: m.tier, cost: advice.cost || 'unknown' };
  if (advice.recommendation) entry.recommendedFor = advice.recommendation;
  if (m.tier === 'ultra' || m.tier === 'critical') {
    entry.warning = 'Ultra/critical-tier model with very high per-request costs. Use sparingly.';
    entry.suggestion = 'For everyday coding, medium-high tier models deliver excellent results at a fraction of the cost.';
  }
  return entry;
}

async function buildModelsResponse(tenant, providers) {
  const allModels = providers.flatMap(p =>
    (p.discoveredModels || []).filter(m => m.visible !== false).map(m => enrichModel(m, p.name))
  );
  const byTier = (tiers) => allModels.filter(m => tiers.includes(m.tier)).slice(0, 3).map(m => m.id);

  return {
    tenant: { slug: tenant.slug, name: tenant.name, _id: tenant._id },
    models: [
      { id: 'model-prism', name: 'Model Prism (Auto Router)', locked: true, selected: true, tier: 'auto',
        recommendedFor: 'all tasks — automatically selects the optimal model',
        suggestion: 'Best default choice. The auto-router classifies your prompt and picks the right model.' },
      ...allModels.map(m => ({ ...m, selected: false })),
    ],
    recommendations: {
      autocomplete: { description: 'For tab-autocomplete / FIM, use cheap fast models:', models: byTier(['micro', 'minimal', 'low']), tiers: ['micro', 'minimal', 'low'] },
      smallTasks: { description: 'For quick questions, simple code — affordable and fast:', models: byTier(['low', 'medium']), tiers: ['low', 'medium'] },
      recommended: { description: 'Best balance of quality and cost for everyday coding:', models: byTier(['medium', 'high']), tiers: ['medium', 'high'] },
      premium: { description: 'Ultra-tier: use only for formal proofs, critical security audits, or when cheaper models fail.',
        models: allModels.filter(m => m.tier === 'ultra' || m.tier === 'critical').map(m => m.id), tiers: ['ultra', 'critical'] },
    },
    formats: ['continue', 'opencode'],
  };
}

async function generateConfig(tenant, providers, { format = 'opencode', selectedIds, apiKey = 'YOUR_API_KEY', baseUrl }) {
  let allModels = providers.flatMap(p =>
    (p.discoveredModels || []).filter(m => m.visible !== false).map(m => ({ id: m.id, tier: m.tier }))
  );
  if (selectedIds?.length) allModels = allModels.filter(m => selectedIds.includes(m.id));

  const url = baseUrl || `https://your-instance/api/${tenant.slug}/v1`;

  const modelIds = allModels.map(m => m.id);

  if (format === 'continue') {
    const lines = [
      `# Continue.dev config — generated by Model Prism for tenant "${tenant.name}"`,
      `# Generated: ${new Date().toISOString()}`,
      `# Recommendation: Use "Model Prism (Auto Router)" as your primary model.`,
      ``, `models:`,
      `  - title: "Model Prism (Auto Router)"`, `    provider: openai`, `    model: auto-prism`,
      `    apiBase: "${url}"`, `    apiKey: "${apiKey}"`, ``,
      ...allModels.map(m => [
        `  - title: "${m.id}"`, `    provider: openai`, `    model: "${m.id}"`,
        `    apiBase: "${url}"`, `    apiKey: "${apiKey}"`,
      ].join('\n')),
      ``, `tabAutocompleteModel:`,
      `  title: "Model Prism (FIM)"`, `  provider: openai`, `  model: auto-prism`,
      `  apiBase: "${url}"`, `  apiKey: "${apiKey}"`,
    ];
    return lines.join('\n');
  }

  if (format === 'openwebui') {
    return JSON.stringify({
      _comment: 'Open WebUI: Admin → Settings → Connections → Add OpenAI Connection',
      url: url,
      key: apiKey,
      name: `Model Prism (${tenant.name})`,
      models: ['auto-prism', ...modelIds],
      instructions: `1. Go to Admin → Settings → Connections\n2. Click "+" under OpenAI Connections\n3. URL: ${url}\n4. Key: ${apiKey}\n5. Save — all models will auto-discover`,
    }, null, 2);
  }

  // Default: opencode
  const modelMap = { 'model-prism': { name: 'Model Prism (Auto Router)' } };
  for (const m of allModels) modelMap[m.id] = { name: m.id };
  return { $schema: 'https://opencode.ai/config.json',
    provider: { 'model-prism': { options: { baseURL: url, apiKey }, models: modelMap } },
    model: 'model-prism/model-prism', compaction: { auto: true, prune: true } };
}

async function resolveTenantAndProviders(tenantIdOrSlug) {
  let tenant;
  if (tenantIdOrSlug) {
    tenant = await Tenant.findById(tenantIdOrSlug).lean().catch(() => null)
      || await Tenant.findOne({ slug: tenantIdOrSlug, active: true }).lean();
  }
  if (!tenant) tenant = await Tenant.findOne({ isDefault: true }).lean();
  if (!tenant) return null;
  const providers = await Provider.find(tenant.providerIds?.length ? { _id: { $in: tenant.providerIds } } : {}).lean();
  return { tenant, providers };
}

// ── Settings helpers ─────────────────────────────────────────────────────────

async function getIdeSettings() {
  const enabled = await SystemConfig.findOne({ key: 'ide_config_public_enabled' }).lean();
  const tenants = await SystemConfig.findOne({ key: 'ide_config_public_tenants' }).lean();
  return {
    publicEnabled: enabled?.value ?? false,
    publicTenantIds: tenants?.value ?? [], // empty = default tenant only
  };
}

// ── Admin endpoints ──────────────────────────────────────────────────────────

// GET /tenants — tenants visible to the current user (RBAC-filtered)
// Admins/maintainers see all; tenant-scoped users see only their tenant.
router.get('/tenants', anyUser, async (req, res) => {
  try {
    const role = req.user?.role || '';
    const isFull = ['admin', 'maintainer', 'finops', 'auditor'].includes(role);
    let tenants;
    if (isFull) {
      tenants = await Tenant.find({ active: true }).select('slug name isDefault').lean();
    } else {
      // Tenant-scoped user — only show their assigned tenant
      const tenantId = req.user?.tenantId;
      if (tenantId) {
        tenants = await Tenant.find({ _id: tenantId, active: true }).select('slug name isDefault').lean();
      } else {
        // Fallback: default tenant only
        tenants = await Tenant.find({ isDefault: true, active: true }).select('slug name isDefault').lean();
      }
    }
    res.json(tenants);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// GET /settings — public config page settings
router.get('/settings', anyUser, async (_req, res) => {
  try { res.json(await getIdeSettings()); }
  catch (err) { res.status(500).json({ error: err.message }); }
});

// PUT /settings — update public config page settings
router.put('/settings', adminOnly, async (req, res) => {
  try {
    const { publicEnabled, publicTenantIds } = req.body;
    if (publicEnabled !== undefined) {
      await SystemConfig.findOneAndUpdate({ key: 'ide_config_public_enabled' }, { value: publicEnabled }, { upsert: true });
    }
    if (publicTenantIds !== undefined) {
      await SystemConfig.findOneAndUpdate({ key: 'ide_config_public_tenants' }, { value: publicTenantIds }, { upsert: true });
    }
    res.json(await getIdeSettings());
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// GET /models?tenant=<id|slug> — models for a specific tenant
router.get('/models', anyUser, async (req, res) => {
  try {
    const resolved = await resolveTenantAndProviders(req.query.tenant);
    if (!resolved) return res.status(404).json({ error: 'Tenant not found' });
    res.json(await buildModelsResponse(resolved.tenant, resolved.providers));
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// POST /generate — generate config for any tenant (admin)
router.post('/generate', anyUser, async (req, res) => {
  try {
    const { format, models: selectedIds, apiKey, tenant: tenantId } = req.body;
    const resolved = await resolveTenantAndProviders(tenantId);
    if (!resolved) return res.status(404).json({ error: 'Tenant not found' });
    const baseUrl = `${req.protocol}://${req.get('host')}/api/${resolved.tenant.slug}/v1`;
    const result = await generateConfig(resolved.tenant, resolved.providers, { format, selectedIds, apiKey, baseUrl });
    if (typeof result === 'string') {
      res.setHeader('Content-Type', 'text/yaml; charset=utf-8');
      return res.send(result);
    }
    res.json(result);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

export default router;

// ── Public endpoints (mounted separately, no auth) ──────────────────────────

export const publicRouter = Router();

// GET /tenants — only tenants enabled for public config
publicRouter.get('/tenants', async (_req, res) => {
  try {
    const settings = await getIdeSettings();
    if (!settings.publicEnabled) return res.json([]);
    let tenants;
    if (settings.publicTenantIds.length) {
      tenants = await Tenant.find({ _id: { $in: settings.publicTenantIds }, active: true }).select('slug name').lean();
    } else {
      tenants = await Tenant.find({ isDefault: true, active: true }).select('slug name').lean();
    }
    res.json(tenants);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// GET /models?tenant=<slug> — models for a public-enabled tenant
publicRouter.get('/models', async (req, res) => {
  try {
    const settings = await getIdeSettings();
    if (!settings.publicEnabled) return res.status(403).json({ error: 'Public config page is disabled' });

    const resolved = await resolveTenantAndProviders(req.query.tenant);
    if (!resolved) return res.status(404).json({ error: 'Tenant not found' });

    // Verify this tenant is allowed for public access
    if (settings.publicTenantIds.length && !settings.publicTenantIds.includes(String(resolved.tenant._id))) {
      // Check if it's the default tenant (always allowed when no specific tenants are selected)
      if (!resolved.tenant.isDefault) return res.status(403).json({ error: 'This tenant is not enabled for public config' });
    }

    res.json(await buildModelsResponse(resolved.tenant, resolved.providers));
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// POST /generate — generate config for a public-enabled tenant
publicRouter.post('/generate', async (req, res) => {
  try {
    const settings = await getIdeSettings();
    if (!settings.publicEnabled) return res.status(403).json({ error: 'Public config page is disabled' });

    const { format, models: selectedIds, apiKey, tenant: tenantSlug } = req.body;
    const resolved = await resolveTenantAndProviders(tenantSlug);
    if (!resolved) return res.status(404).json({ error: 'Tenant not found' });

    if (settings.publicTenantIds.length && !settings.publicTenantIds.includes(String(resolved.tenant._id))) {
      if (!resolved.tenant.isDefault) return res.status(403).json({ error: 'This tenant is not enabled for public config' });
    }

    const baseUrl = `${req.protocol}://${req.get('host')}/api/${resolved.tenant.slug}/v1`;
    const result = await generateConfig(resolved.tenant, resolved.providers, { format, selectedIds, apiKey, baseUrl });
    if (typeof result === 'string') {
      res.setHeader('Content-Type', 'text/yaml; charset=utf-8');
      return res.send(result);
    }
    res.json(result);
  } catch (err) { res.status(500).json({ error: err.message }); }
});
